from __future__ import annotations

import re
from typing import Any, Literal

from pydantic import BaseModel, model_validator

from fedotmas._settings import validate_model_name
from fedotmas.common.logging import get_logger
from fedotmas.maw._validators import (
    auto_fill_agent_name,
    validate_node_refs,
    warn_terminal_parallel,
    warn_unused_agents,
)

_log = get_logger("fedotmas.maw.models")

_STATE_VAR_RE = re.compile(r"\{(\w+)\}")
_ANGLE_VAR_RE = re.compile(r"<(\w+)>")


class AgentPoolEntry(BaseModel):
    """A single agent definition for stage-1 pool generation.

    Unlike ``MAWAgentConfig``, this does **not** carry ``output_key`` — wiring
    is a stage-2 concern.
    """

    name: str
    instruction: str
    model: str | None = None
    tools: list[str] = []


class AgentPoolConfig(BaseModel):
    """Agent pool produced by stage-1 of two-stage generation."""

    agents: list[AgentPoolEntry]

    @model_validator(mode="after")
    def _unique_names(self) -> AgentPoolConfig:
        seen: set[str] = set()
        for a in self.agents:
            if a.name in seen:
                raise ValueError(f"Duplicate agent name in pool: '{a.name}'")
            seen.add(a.name)
        return self


class MAWAgentConfig(BaseModel):
    """Configuration for a single LLM agent."""

    name: str
    instruction: str
    model: str | None = None
    output_key: str
    tools: list[str] = []

    @model_validator(mode="after")
    def _normalize_fields(self) -> MAWAgentConfig:
        validate_model_name(self.model)

        # Normalize instruction: <var> → {var} → {var?}
        instr = _ANGLE_VAR_RE.sub(r"{\1}", self.instruction)
        self.instruction = _STATE_VAR_RE.sub(r"{\1?}", instr)
        return self


class MAWStepConfig(BaseModel):
    """A node in the pipeline tree."""

    type: Literal["agent", "sequential", "parallel", "loop"]

    # For type="agent": reference to an agent config by name.
    agent_name: str | None = None

    # For type="sequential" / "parallel" / "loop": ordered child nodes.
    children: list[MAWStepConfig] = []

    # For type="loop": max iterations before forced exit.
    max_iterations: int | None = None

    @model_validator(mode="before")
    @classmethod
    def _infer_type(cls, data: Any) -> Any:
        """Auto-fill missing ``type`` based on other fields present."""
        if not isinstance(data, dict):
            return data
        if "agent_name" in data and data.get("children"):
            raise ValueError("Cannot specify both 'agent_name' and 'children'")
        if "type" not in data:
            data = dict(data)  # avoid mutating the original
            if "agent_name" in data:
                data["type"] = "agent"
            elif "children" in data:
                data["type"] = "sequential"
        return data


class MAWConfig(BaseModel):
    """Complete pipeline configuration generated by the meta-agent."""

    agents: list[MAWAgentConfig]
    pipeline: MAWStepConfig

    @model_validator(mode="after")
    def _validate_config(self) -> MAWConfig:
        agent_names = {a.name for a in self.agents}

        if len(self.agents) == 1:
            auto_fill_agent_name(self.pipeline, self.agents[0].name)

        # Unique agent names
        if len(agent_names) != len(self.agents):
            seen: set[str] = set()
            for a in self.agents:
                if a.name in seen:
                    raise ValueError(f"Duplicate agent name: '{a.name}'")
                seen.add(a.name)

        # Unique output keys
        output_keys = [a.output_key for a in self.agents]
        if len(set(output_keys)) != len(output_keys):
            seen_keys: set[str] = set()
            for a in self.agents:
                if a.output_key in seen_keys:
                    raise ValueError(f"Duplicate output_key: '{a.output_key}'")
                seen_keys.add(a.output_key)

        validate_node_refs(self.pipeline, agent_names)
        warn_unused_agents(self.pipeline, agent_names)
        warn_terminal_parallel(self.pipeline)

        return self
