import logging
import os
import pandas as pd

from dotenv import load_dotenv
from langchain_core.messages import SystemMessage, HumanMessage
from langchain.tools.render import render_text_description
from langchain_core.tools import tool
from protollm.connectors import create_llm_connector
from pathlib import Path

from ChemCoScientist.paper_analysis.chroma_db_operations import ChromaDBPaperStore
from ChemCoScientist.paper_analysis.prompts import paraphrase_prompt
from ChemCoScientist.paper_analysis.question_processing import process_question, simple_query_llm
from ChemCoScientist.paper_analysis.dataset_collection import extract_mols_prop_dataset
from ChemCoScientist.frontend.memory import SELECTED_PAPERS
from definitions import CONFIG_PATH

load_dotenv(CONFIG_PATH)
VISION_LLM_URL = os.environ["VISION_LLM_URL"]

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@tool
def explore_chemistry_database(task: str) -> dict:
    """
    Leverages a database of chemical scientific papers to answer user questions.
    This tool is prioritized over web searches for information.
    It is designed for general inquiries and not for details specific to individual papers
    (e.g., figure descriptions, experimental details, conclusions) or for identifying
    lists of relevant publications.
    
    Args:
        task (str): The user's question or query related to chemistry.
    
    Returns:
        dict: A dictionary containing the LLM's response, the supporting
            text, images, and tables extracted from the database, and metadata
            about the request (model used, token count, etc.).
    """
    try:
        print('Running explore_chemistry_database tool...')
        print(f'task: {task}')
        paper_store = ChromaDBPaperStore()
        return process_question(task, paper_store)
    except Exception as e:
        logger.error(f'explore_chemistry_database ERROR: {e}')
        return {'answer': 'Could not extract any data from DB.'}


@tool
def explore_my_papers(task: str, session_id: str = None) -> dict:
    """
    Answers questions based on the content of user-provided scientific papers. 
    This tool allows users to query specific documents they've uploaded, retrieving insights 
    like figure descriptions, experimental details, or conclusions. It prioritizes answers
    from these papers over general web searches.
    
    Args:
        task (str): The user's question about the uploaded papers.
        session_id (str, optional):  A unique identifier for the user's session, primarily used for frontend integration. Defaults to None.
    
    Returns:
        dict: A dictionary containing the answer generated by the LLM and metadata 
              about the request (e.g., model used, token count).  
              Returns an error message if no papers are provided or if data extraction fails.
    """
    print('Running explore_my_papers tool...')
    print(f'task: {task}')
    try:
        # TODO: remove when proper frontend is added
        if not SELECTED_PAPERS:
            directory = Path(os.environ.get('MY_PAPERS_PATH'))
            papers = [str(f.resolve()) for f in directory.iterdir() if f.is_file() and f.suffix.lower() == '.pdf']

            if not papers:
                return {'answer': 'No papers provided for search.'}
        else:
            if not SELECTED_PAPERS.get(session_id, []):
                return {'answer': 'No papers provided for search.'}
            papers = SELECTED_PAPERS[session_id]

        return simple_query_llm(VISION_LLM_URL, task, papers)
    except Exception as e:
        logger.error(f'explore_my_papers ERROR: {e}')
        return {'answer': 'Could not extract any data from uploaded papers.'}


def paraphrase_query(query: str) -> dict:
    """
    Transforms a user's chemistry question into a refined query optimized for finding relevant scientific papers.
    
    Args:
        query (str): The user's initial question about a chemistry topic.
    
    Returns:
        dict: A dictionary containing the paraphrased query as 'answer'. This improved query aims to enhance the accuracy and effectiveness of searches for related research papers.
    """
    llm = create_llm_connector(VISION_LLM_URL)

    user_message = {"type": "text", "text": f"USER QUESTION: {query}"}

    messages = [
        SystemMessage(content=paraphrase_prompt),
        HumanMessage(content=user_message),
    ]

    res = llm.invoke(messages)
    return {'answer': res.content}


@tool
def select_papers(query: str, papers_num: int = 15, final_papers_num: int = 3) -> dict:
    """
    Retrieves relevant chemical scientific papers based on a user's query. This tool prioritizes searching a dedicated paper database before resorting to broader web searches, ensuring focused and accurate results. It's designed specifically for requests to list papers, not for general question answering.
    
    Args:
        query (str): The user's search query.
        papers_num (int, optional): The initial number of papers to retrieve from the vector storage for consideration. Defaults to 15.
        final_papers_num (int, optional): The desired number of papers to return after re-ranking. Defaults to 3.
    
    Returns:
        dict: A dictionary containing the retrieved papers.  Returns an error message if no papers are found.
    """
    try:
        print('Running select_papers tool...')
        print(f'query: {query}')
        paper_store = ChromaDBPaperStore()
        return paper_store.search_for_papers(query, papers_num, final_papers_num)
    except Exception as e:
        logger.error(f'select_papers ERROR: {e}')
        return {'answer': 'Could not find any papers in DB.'}

@tool
def create_dataset_from_papers(task: str, session_id: str = None) -> pd.DataFrame:
    """
    Creates a structured molecular property dataset from a collection of research papers (PDFs).
    
    Args:
        task (str): A natural-language description of the property or dataset to extract.
            Examples:
                - "Extract MIC values for all compounds against Staphylococcus aureus"
                - "Create a dataset of compounds with reported solubility and melting point"
        session_id (str, optional): An identifier for the current user session.
            Used to access session-specific uploaded papers from `SELECTED_PAPERS`.

    Returns:
        pd.DataFrame: Dataset containing the extraction results:
                'id' — molecule identifier
                'smiles' — molecular structure in SMILES format
                extracted property columns (e.g., MIC, IC50, solubility)
                'units' - units of the extracted property
                `source` — filename of the originating paper
    """
    print('Running create_dataset_from_papers tool...')
    print(f'task: {task}')
    try:
        # TODO: remove when proper frontend is added
        if not SELECTED_PAPERS:
            directory = Path(os.environ.get('MY_PAPERS_PATH'))
            papers = [str(f.resolve()) for f in directory.iterdir() if f.is_file() and f.suffix.lower() == '.pdf']

            if not papers:
                return {'answer': 'No papers provided for search.'}
        else:
            if not SELECTED_PAPERS.get(session_id, []):
                return {'answer': 'No papers provided for search.'}
            papers = SELECTED_PAPERS[session_id]

        return extract_mols_prop_dataset(VISION_LLM_URL, task, papers)
    except Exception as e:
        logger.error(f'explore_my_papers ERROR: {e}')
        return {'answer': 'Could not extract any data from uploaded papers.'}

paper_analysis_tools = [
    explore_chemistry_database,
    explore_my_papers,
    select_papers,
    create_dataset_from_papers
]

paper_analysis_tools_rendered = render_text_description(paper_analysis_tools)
