import base64
import os

from dotenv import load_dotenv
from langchain_core.messages import SystemMessage
from protollm.connectors import create_llm_connector

from ChemCoScientist.paper_analysis.chroma_db_operations import ChromaDBPaperStore
from ChemCoScientist.paper_analysis.prompts import sys_prompt, explore_my_papers_prompt
from ChemCoScientist.paper_analysis.settings import allowed_providers
from CoScientist.paper_parser.utils import convert_to_base64, prompt_func
from definitions import CONFIG_PATH

load_dotenv(CONFIG_PATH)

VISION_LLM_URL = os.environ["VISION_LLM_URL"]

PAPER_STORE = ChromaDBPaperStore()


def query_llm(
    model_url: str, question: str, txt_context: str, img_paths: list[str]
) -> tuple:
    """
    Queries a Large Language Model (LLM) to answer questions using provided context.

    This method constructs a query incorporating both textual and visual information, then sends it to the specified
    LLM. This allows the LLM to leverage diverse data sources for a more informed response.

    Args:
        model_url (str): The URL of the LLM model to use for querying.
        question (str): The question to be answered by the LLM.
        txt_context (str): Textual information to provide context for the question.
        img_paths (list[str]): A list of file paths to images to be used as context.

    Returns:
        tuple: A tuple containing the LLM's response content (str) and a dictionary of response metadata (dict).
    """
    llm = create_llm_connector(model_url, extra_body={"provider": {"only": allowed_providers}})

    img_context = list(map(convert_to_base64, img_paths))

    messages = [
        SystemMessage(content=sys_prompt),
        prompt_func(
            {
                "text": f"USER QUESTION: {question}\n\nCONTEXT: {txt_context}",
                "image": img_context,
            }
        ),
    ]

    res = llm.invoke(messages)
    return res.content, res.response_metadata


def simple_query_llm(model_url: str, question: str, pdfs: list,) -> dict:
    """
    Queries a language model with a question and a list of PDF documents to provide context for answering the question.

    Args:
        model_url (str): The URL of the language model to use for querying.
        question (str): The question to ask the language model.
        pdfs (list): A list of paths to PDF documents to provide as context.

    Returns:
        dict: A dictionary containing the answer from the language model. The dictionary has a single key, 'answer',
            which holds the answer string.
    """
    from ChemCoScientist.frontend.utils import update_activity

    if pdfs:
        update_activity(os.path.dirname(pdfs[0]))
    llm = create_llm_connector(model_url)

    content = []

    for paper_pdf in pdfs:
        with open(paper_pdf, "rb") as f:
            base64_pdf = base64.b64encode(f.read()).decode("utf-8")
        paper_part = {
            "type": "file",
            "file": {
                "filename": paper_pdf,
                "file_data": f"data:application/pdf;base64,{base64_pdf}",
            },
        }
        content.append(paper_part)

    text_part = {"type": "text", "text": f"USER QUESTION: {question}"}
    content.append(text_part)
    from langchain_core.messages import HumanMessage

    messages = [
        SystemMessage(content=explore_my_papers_prompt),
        HumanMessage(content=content)
    ]

    res = llm.invoke(messages)
    return {'answer': res.content}


def process_question(question: str) -> dict:
    """
    Processes a question by retrieving relevant text and image context from scientific papers and querying a Large Language Model (LLM) to generate an answer.

    Args:
        question (str): The input question string.

    Returns:
        dict: A dictionary containing the answer and associated metadata:
            'answer' - the answer generated by the LLM based on the provided context;
            'metadata' - a dictionary containing:
                'text_context' - the concatenated text from relevant paper chunks, including metadata;
                'image_context' - the set of image paths identified as relevant to the question;
                'metadata' - Additional metadata returned by the LLM query.
    """
    txt_data, img_data, papers = PAPER_STORE.retrieve_context(question)
    txt_context = ""
    img_paths = set()

    for idx, chunk in enumerate(txt_data, start=1):
        txt_context += (
            f"{idx}. Metadata: "
            + str(chunk[2])
            + "\nChunk: "
            + chunk[1].replace("passage: ", "")
            + "\n\n"
        )
    for chunk_meta in [chunk[2] for chunk in txt_data]:
        img_paths.update(eval(chunk_meta["imgs_in_chunk"]))
    for img in img_data["metadatas"][0]:
        img_paths.add(img["image_path"])

    ans, metadata = query_llm(VISION_LLM_URL, question, txt_context, list(img_paths))

    return {
        "answer": ans,
        "metadata": {
            "text_context": txt_context,
            "image_context": img_paths,
            "metadata": metadata,
        },
    }


if __name__ == "__main__":
    # file_paths = []  # Enter list of paths to images here
    #
    # images = list(map(convert_to_base64, file_paths))
    #
    # llm = create_llm_connector(VISION_LLM_URL)
    #
    # # question = ("Какая реакция идет протекает на 6 стадии Total Synthesis of (−)-Glionitrin A/B? Какие реагенты"
    # #             " участвовали в реакции и какой продукт получили? Какой получился выход?")
    # question = ("I need all the compounds that were used in the experiments. Obligatorily I need all results to be in"
    #             " the form of a table of 2 columns where in the first column were the names by IUPAC numberclature and"
    #             " in the second column in SMILES notation. Don't add it to this list of reaction products for me. Can"
    #             " you do that?")
    # context = ""
    #
    # messages = [
    #     SystemMessage(content=sys_prompt),
    #     prompt_func({"text": f"USER QUESTION: {question}\n\nCONTEXT: {context}", "image": images})
    # ]
    # # messages = [
    # #     SystemMessage(content="You're a useful assistant. You only ever reply in the form of valid JSON."),
    # #     prompt_func(
    # #         {
    # #             "text": "For the provided images, generate a detailed clear description. If there is a table in the"
    # #                     " image, parse it and return it in HTML format. If you see chemical compounds in the figures,"
    # #                     " output the names of the compounds according to IUPAC nomenclature.\n"
    # #                     " As a response, return ONLY JSON of the following form: {‘figure_1’:"
    # #                     " ‘figure_1_description’, ‘figure_2’: ‘figure_2_description’, ‘table_1’:"
    # #                     " ‘table_1_description’...}",
    # #             "image": images
    # #         }
    # #     )
    # # ]
    #
    # res = llm.invoke(messages)
    # print(res.content)
    # print(res.response_metadata)

    #######################################################

    query = 'What is the title of an article?'
    # question = 'What components are involved in the synthesis of BASHY dyes, and what are the uses of these dyes?'
    # question = 'What IC50 values do weakly active and highly active Bruton\'s tyrosine kinase inhibitors have?'
    # question = 'How does the synthesis of Glionitrin A/B happen?'

    # res = simple_query_llm(VISION_LLM_URL, question, [paper])
    result = process_question(query)
    from pprint import pprint
    pprint(result)
